/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Administrator.java
 *
 * Created on 11 Dec, 2018, 6:26:45 AM
 */

package cars;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DEll
 */
public class Administrator extends javax.swing.JFrame {

    /** Creates new form Administrator */
    public Administrator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAdmin1_TB = new javax.swing.JTable();
        jPush_L = new javax.swing.JLabel();
        jBack_L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Orders", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jAdmin1_TB.setFont(new java.awt.Font("Century", 0, 12));
        jAdmin1_TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "         S.no", "        Name", "   Phone Number", "        E-Mail", "       Gender", "       D.O.B", "      Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jAdmin1_TB.setGridColor(new java.awt.Color(0, 153, 153));
        jAdmin1_TB.setOpaque(false);
        jAdmin1_TB.setRowHeight(20);
        jAdmin1_TB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jAdmin1_TBPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jAdmin1_TB);

        jPush_L.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPush_L.setForeground(new java.awt.Color(204, 255, 255));
        jPush_L.setText("Administrator");
        jPush_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPush_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPush_LMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
                    .addComponent(jPush_L, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPush_L, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 70, 780, 220);

        jBack_L.setBackground(new java.awt.Color(255, 255, 255));
        jBack_L.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jBack_L.setForeground(new java.awt.Color(51, 0, 51));
        jBack_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/back.png"))); // NOI18N
        jBack_L.setText("Back");
        jBack_L.setOpaque(true);
        jBack_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBack_LMouseEntered(evt);
            }
        });
        getContentPane().add(jBack_L);
        jBack_L.setBounds(0, 0, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/admin.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-100, 0, 970, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPush_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPush_LMouseClicked
        // TODO add your handling code here:
        DefaultTableModel table1=(DefaultTableModel)jAdmin1_TB.getModel();
        int rows1=table1.getRowCount();
        while(rows1>0){
            table1.removeRow(0);
            rows1--;
        }
        
        int i=0;
        try{
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
            Statement stmt=con.createStatement();

             String query1="select* from sign_up;";
               ResultSet rs1=stmt.executeQuery(query1);
            
           while(rs1.next()){
               i++;
               String name=rs1.getString("name");
               int pno=rs1.getInt("phone_no");
               String email=rs1.getString("email");
               String address=rs1.getString("address");
               String gender=rs1.getString("sex");
                String dob=rs1.getString("dateofbirth");
               table1.addRow(new Object[]{i,name,pno,email,gender,dob,address});
           }
                
               con.close();
               stmt.close();
               rs1.close();
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jPush_LMouseClicked

    private void jBack_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseClicked
        // TODO add your handling code here:
        new About_us().setVisible(true);
        dispose();
}//GEN-LAST:event_jBack_LMouseClicked

    private void jBack_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseEntered
        // TODO add your handling code here:
        jBack_L.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_jBack_LMouseEntered

    private void jPush_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPush_LMouseEntered
        // TODO add your handling code here:
        jPush_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
    }//GEN-LAST:event_jPush_LMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jAdmin1_TBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jAdmin1_TBPropertyChange
        // TODO add your handling code here:
         DefaultTableCellRenderer stringRenderer = (DefaultTableCellRenderer)
         jAdmin1_TB.getDefaultRenderer(String.class);
         stringRenderer.setHorizontalAlignment(SwingConstants.CENTER);
    }//GEN-LAST:event_jAdmin1_TBPropertyChange

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jAdmin1_TB;
    private javax.swing.JLabel jBack_L;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPush_L;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
