/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Bike.java
 *
 * Created on 11 Dec, 2018, 6:25:17 AM
 */

package cars;
import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author DEll
 */
public class Bike extends javax.swing.JFrame {

    /** Creates new form Bike */
    public Bike() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jData_TA = new javax.swing.JTextArea();
        jHaya_BT = new javax.swing.JButton();
        jKawaski_BT = new javax.swing.JButton();
        jBuy_L = new javax.swing.JLabel();
        jDodge_BT = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jModel_CB = new javax.swing.JComboBox();
        jImage1_L = new javax.swing.JLabel();
        jImage3_L = new javax.swing.JLabel();
        jImage4_L = new javax.swing.JLabel();
        jImage2_L = new javax.swing.JLabel();
        jBack_L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nyala", 0, 36));
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Bikes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 30, 120, 40);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jData_TA.setColumns(20);
        jData_TA.setRows(5);
        jScrollPane1.setViewportView(jData_TA);

        jHaya_BT.setFont(new java.awt.Font("Century", 0, 14));
        jHaya_BT.setText("Hayabusa");
        jHaya_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jHaya_BTMouseEntered(evt);
            }
        });
        jHaya_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHaya_BTActionPerformed(evt);
            }
        });

        jKawaski_BT.setFont(new java.awt.Font("Century", 0, 14));
        jKawaski_BT.setText("Kawaski");
        jKawaski_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jKawaski_BTMouseEntered(evt);
            }
        });
        jKawaski_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKawaski_BTActionPerformed(evt);
            }
        });

        jBuy_L.setFont(new java.awt.Font("Century", 0, 18));
        jBuy_L.setForeground(new java.awt.Color(204, 255, 255));
        jBuy_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBuy_L.setText("Buy Now");
        jBuy_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuy_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBuy_LMouseEntered(evt);
            }
        });

        jDodge_BT.setFont(new java.awt.Font("Century", 0, 14));
        jDodge_BT.setText("Dodge ");
        jDodge_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDodge_BTMouseEntered(evt);
            }
        });
        jDodge_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodge_BTActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });

        jModel_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jModel_CB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jModel_CBPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jHaya_BT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jKawaski_BT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDodge_BT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jModel_CB, 0, 0, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 18, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBuy_L, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHaya_BT)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jKawaski_BT)
                        .addGap(18, 18, 18)
                        .addComponent(jDodge_BT))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jModel_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBuy_L, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jImage1_L.setBackground(new java.awt.Color(0, 0, 51));
        jImage1_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImage1_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/download (6).jpg"))); // NOI18N
        jImage1_L.setOpaque(true);
        jImage1_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage1_LMouseEntered(evt);
            }
        });

        jImage3_L.setBackground(new java.awt.Color(0, 0, 51));
        jImage3_L.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jImage3_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/download (7).jpg"))); // NOI18N
        jImage3_L.setOpaque(true);
        jImage3_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage3_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage3_LMouseEntered(evt);
            }
        });

        jImage4_L.setBackground(new java.awt.Color(0, 0, 51));
        jImage4_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/download (2).jpg"))); // NOI18N
        jImage4_L.setOpaque(true);
        jImage4_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage4_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage4_LMouseEntered(evt);
            }
        });

        jImage2_L.setBackground(new java.awt.Color(0, 0, 51));
        jImage2_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/download (2).jpg"))); // NOI18N
        jImage2_L.setOpaque(true);
        jImage2_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage2_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage2_LMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jImage1_L, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jImage4_L, 0, 0, Short.MAX_VALUE)
                    .addComponent(jImage2_L, 0, 0, Short.MAX_VALUE)
                    .addComponent(jImage3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jImage2_L, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jImage3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jImage4_L, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jImage1_L, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 80, 920, 340);

        jBack_L.setBackground(new java.awt.Color(255, 255, 255));
        jBack_L.setFont(new java.awt.Font("Nyala", 0, 18));
        jBack_L.setForeground(new java.awt.Color(51, 0, 51));
        jBack_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/back.png"))); // NOI18N
        jBack_L.setText("Back");
        jBack_L.setOpaque(true);
        jBack_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBack_LMouseEntered(evt);
            }
        });
        getContentPane().add(jBack_L);
        jBack_L.setBounds(0, 0, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/bike.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHaya_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHaya_BTActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(0);
        jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\hbike_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\hbike_4.jpg"));
        jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\hbike_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\hbike_2.jpg"));
          jData_TA.setText("Information\n you have chosen Hayabusa Bikes");
}//GEN-LAST:event_jHaya_BTActionPerformed

    private void jKawaski_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKawaski_BTActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(1);
        jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\kbike_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\kbike_4.jpg"));
         jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\kbike_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\kbike_2.jpg"));
          jData_TA.setText("Information\n you have chosen Kawaski Bikes");
    }//GEN-LAST:event_jKawaski_BTActionPerformed

    private void jDodge_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodge_BTActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(2);
        jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\dbike_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\dbike_4.jpg"));
        jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\dbike_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\dbike_2.jpg"));
          jData_TA.setText("Information\n you have chosen Dodge Bikes");
    }//GEN-LAST:event_jDodge_BTActionPerformed

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:
        jComboBox1.setVisible(false);
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jBuy_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuy_LMouseClicked
        // TODO add your handling code here:
        try{
         String model="a";
        int price=0;
        int index1=jComboBox1.getSelectedIndex();
        int mindex=jModel_CB.getSelectedIndex();
        if(index1==0){
                     if(mindex==0){
                         model="H1"; price=60000;
                                }
                     else
                     if(mindex==1){
                         model="H2"; price=50000;
                                }
                     else
                     if(mindex==2){
                         model="H3"; price=40000;
                                }
        }
         else
         if(index1==1){
                     if(mindex==0){
                         model="K1"; price=50000;
                                }
                     else
                     if(mindex==1){
                         model="K2"; price=60000;
                                }
                     else
                     if(mindex==2){
                         model="K3"; price=45000;
                                }
                       }
        else
         if(index1==2){
                     if(mindex==0){
                         model="D1"; price=60000;
                                }
                     else
                     if(mindex==1){
                         model="D2"; price=65000;
                                }
                     else
                     if(mindex==2){
                         model="D3"; price=75000;
                                }
                       }
                String id1=JOptionPane.showInputDialog(this, "Please Enter your id number");
                  int id=Integer.parseInt(id1);


         Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
            Statement stmt=con.createStatement();
            
            String query="select id from sign_up;";
            ResultSet rs=stmt.executeQuery(query);
           
            while(rs.next()){
                   if(id==rs.getInt("id")){   
            String query1="insert into recycle values('"+model+"',"+price+",'"+"Bike"+"',"+id+");";
            int rs1=stmt.executeUpdate(query1);
            new Order().setVisible(true);}
                   else
                   { JOptionPane.showMessageDialog(this, "No account exist with this ID");}
            }
            con.close();
            stmt.close();
        }
        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jBuy_LMouseClicked

    private void jModel_CBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jModel_CBPropertyChange
        // TODO add your handling code here:
        jModel_CB.setVisible(false);

    }//GEN-LAST:event_jModel_CBPropertyChange

    private void jBack_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseClicked
        // TODO add your handling code here:
        new Vehicle().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBack_LMouseClicked

    private void jBack_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseEntered
        // TODO add your handling code here:
        jBack_L.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_jBack_LMouseEntered

    private void jBuy_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuy_LMouseEntered
        // TODO add your handling code here:
        jBuy_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBuy_LMouseEntered

    private void jDodge_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDodge_BTMouseEntered
        // TODO add your handling code here:
        jDodge_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jDodge_BTMouseEntered

    private void jKawaski_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKawaski_BTMouseEntered
        // TODO add your handling code here:
    jKawaski_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jKawaski_BTMouseEntered

    private void jHaya_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHaya_BTMouseEntered
        // TODO add your handling code here:
        jHaya_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jHaya_BTMouseEntered

    private void jImage1_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage1_LMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jImage1_LMouseEntered

    private void jImage2_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage2_LMouseEntered
        // TODO add your handling code here:
        jImage2_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jImage2_LMouseEntered

    private void jImage2_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage2_LMouseClicked
        // TODO add your handling code here:
        jModel_CB.setSelectedIndex(0);
        if(jComboBox1.getSelectedIndex()==0){
            jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\hbike_2.jpg"));
            jData_TA.setText("Hayabusa \n Max Speed:  253kmph\nAverage:  29kmpl\nModelno:  H1");
        } else
            if(jComboBox1.getSelectedIndex()==1){
                jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\kbike_2.jpg"));
                jData_TA.setText("Kawaski\n Max Speed:  295kmph\nAverage:  30kmpl\nModelno:  K1");
            } else
                if(jComboBox1.getSelectedIndex()==2){
                    jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\dbike_2.jpg"));
                    jData_TA.setText("Dodge \n Max Speed:  255kmph\nAverage:  31kmpl\nModelno:  D1");
                } else
                    jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backbike.jpg"));
}//GEN-LAST:event_jImage2_LMouseClicked

    private void jImage3_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage3_LMouseClicked
        // TODO add your handling code here:
        jModel_CB.setSelectedIndex(1);
        if(jComboBox1.getSelectedIndex()==0){
            jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\hbike_3.jpg"));
            jData_TA.setText("Hayabusa \n Max Speed:  254kmph\nAverage:  45kmpl\nModelno:  H2");
        } else
            if(jComboBox1.getSelectedIndex()==1){
                jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\kbike_3.jpg"));
                jData_TA.setText("Kawaski\n Max Speed:  295kmph\nAverage:  33kmpl\nModelno:  K2");
            } else
                if(jComboBox1.getSelectedIndex()==2){
                    jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\dbike_3.jpg"));
                    jData_TA.setText("Dodge \n Max Speed:  256kmph\nAverage:  32kmpl\nModelno:  D2");
                } else
                    jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backbike.jpg"));
}//GEN-LAST:event_jImage3_LMouseClicked

    private void jImage3_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage3_LMouseEntered
        // TODO add your handling code here:
        jImage3_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jImage3_LMouseEntered

    private void jImage4_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage4_LMouseClicked
        // TODO add your handling code here:
        jModel_CB.setSelectedIndex(2);
        if(jComboBox1.getSelectedIndex()==0){
            jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\hbike_4.jpg"));
            jData_TA.setText("Hayabusa \n Max Speed:  256kmph\nAverage:  50kmpl\nModelno:  H3");
        } else
            if(jComboBox1.getSelectedIndex()==1){
                jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\kbike_4.jpg"));
                jData_TA.setText("Kawaski\n Max Speed:  297kmph\nAverage:  60kmpl\nModelno:  K3");
            } else
                if(jComboBox1.getSelectedIndex()==2){
                    jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\dbike_4.jpg"));
                    jData_TA.setText("Dodge \n Max Speed:  258kmph\nAverage:  65kmpl\nModelno:  D3");
                } else
                    jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backbike.jpg"));
}//GEN-LAST:event_jImage4_LMouseClicked

    private void jImage4_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage4_LMouseEntered
        // TODO add your handling code here:
        jImage4_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jImage4_LMouseEntered

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBack_L;
    private javax.swing.JLabel jBuy_L;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextArea jData_TA;
    private javax.swing.JButton jDodge_BT;
    private javax.swing.JButton jHaya_BT;
    private javax.swing.JLabel jImage1_L;
    private javax.swing.JLabel jImage2_L;
    private javax.swing.JLabel jImage3_L;
    private javax.swing.JLabel jImage4_L;
    private javax.swing.JButton jKawaski_BT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox jModel_CB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
