/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Car.java
 *
 * Created on 11 Dec, 2018, 6:25:02 AM
 */

package cars;
import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;



/**
 *
 * @author DEll
 */
public class Car extends javax.swing.JFrame {

    /** Creates new form Car */
    public Car() {
        initComponents();
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLykan_BT = new javax.swing.JButton();
        jBMW_BT = new javax.swing.JButton();
        jBMW_CB = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jData_TA = new javax.swing.JTextArea();
        jBuy_L = new javax.swing.JLabel();
        jPagani_BT = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jModel_CB = new javax.swing.JComboBox();
        jImage1_L = new javax.swing.JLabel();
        jImage2_L = new javax.swing.JLabel();
        jImage3_L = new javax.swing.JLabel();
        jImage4_L = new javax.swing.JLabel();
        jBack_L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nyala", 0, 36));
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("Cars");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 30, 140, 50);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLykan_BT.setFont(new java.awt.Font("Century", 0, 14));
        jLykan_BT.setText("Lykan Hypersports");
        jLykan_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLykan_BTMouseEntered(evt);
            }
        });
        jLykan_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLykan_BTActionPerformed(evt);
            }
        });

        jBMW_BT.setFont(new java.awt.Font("Century", 0, 14));
        jBMW_BT.setText("BMW");
        jBMW_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBMW_BTMouseEntered(evt);
            }
        });
        jBMW_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMW_BTActionPerformed(evt);
            }
        });

        jBMW_CB.setFont(new java.awt.Font("Century", 0, 14));
        jBMW_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "i8", "X1", "AMG-GT" }));
        jBMW_CB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jBMW_CBPropertyChange(evt);
            }
        });

        jData_TA.setColumns(20);
        jData_TA.setRows(5);
        jData_TA.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jData_TAPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jData_TA);

        jBuy_L.setFont(new java.awt.Font("Century", 0, 18));
        jBuy_L.setForeground(new java.awt.Color(204, 255, 255));
        jBuy_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBuy_L.setText("Buy Now");
        jBuy_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuy_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBuy_LMouseEntered(evt);
            }
        });

        jPagani_BT.setFont(new java.awt.Font("Century", 0, 14));
        jPagani_BT.setText("Pagani");
        jPagani_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPagani_BTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPagani_BTMouseEntered(evt);
            }
        });
        jPagani_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagani_BTActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });

        jModel_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jModel_CB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jModel_CBPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBMW_BT)
                        .addGap(18, 18, 18)
                        .addComponent(jBMW_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLykan_BT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jPagani_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jModel_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jBuy_L, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBMW_BT)
                    .addComponent(jBMW_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLykan_BT)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPagani_BT)
                    .addComponent(jModel_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jBuy_L, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );

        jImage1_L.setBackground(new java.awt.Color(0, 0, 0));
        jImage1_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImage1_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/4-sports-cars-ford-mustang.jpg"))); // NOI18N
        jImage1_L.setOpaque(true);

        jImage2_L.setBackground(new java.awt.Color(0, 0, 0));
        jImage2_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/0c5497.jpg"))); // NOI18N
        jImage2_L.setOpaque(true);
        jImage2_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage2_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage2_LMouseEntered(evt);
            }
        });

        jImage3_L.setBackground(new java.awt.Color(0, 0, 0));
        jImage3_L.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jImage3_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/download (4).jpg"))); // NOI18N
        jImage3_L.setOpaque(true);
        jImage3_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage3_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage3_LMouseEntered(evt);
            }
        });

        jImage4_L.setBackground(new java.awt.Color(0, 0, 0));
        jImage4_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/bmw.jpg"))); // NOI18N
        jImage4_L.setOpaque(true);
        jImage4_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage4_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage4_LMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jImage1_L, javax.swing.GroupLayout.PREFERRED_SIZE, 538, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jImage4_L, 0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jImage2_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jImage3_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jImage2_L, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jImage3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jImage4_L, 0, 0, Short.MAX_VALUE))
                        .addComponent(jImage1_L, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 980, 320);

        jBack_L.setBackground(new java.awt.Color(255, 255, 255));
        jBack_L.setFont(new java.awt.Font("Nyala", 0, 18));
        jBack_L.setForeground(new java.awt.Color(51, 0, 51));
        jBack_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/back.png"))); // NOI18N
        jBack_L.setText("Back");
        jBack_L.setOpaque(true);
        jBack_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBack_LMouseEntered(evt);
            }
        });
        getContentPane().add(jBack_L);
        jBack_L.setBounds(0, 0, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/radiation_sign_spot_86968_1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuy_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuy_LMouseEntered
        // TODO add your handling code here:
        jBuy_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jBuy_LMouseEntered

    private void jBuy_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuy_LMouseClicked
        // TODO add your handling code here:
        String model="a";
        int price=0;
        int index=jBMW_CB.getSelectedIndex();
        int index1=jComboBox1.getSelectedIndex();
        int mindex=jModel_CB.getSelectedIndex();
     if(index1==0){
            if(index==0){
                       model="BI1"; price=2500000;
                         }
              else
            if(index==1){
                       model="BX1"; price=2400000;
                         }
              else
            if(index==2){
                       model="BG1"; price=2300000;
                         }
       }
else
    if(index1==1){
                     if(mindex==0){
                         model="LK1"; price=3000000;
                                }
                     else
                     if(mindex==1){
                         model="LK2"; price=3200000;
                                }
                     else
                     if(mindex==0){
                         model="LK3"; price=3300000;
                                }
            }
    else
        if(index1==2){
                     if(mindex==0){
                         model="PG1"; price=3600000;
                                }
                     else
                     if(mindex==1){
                         model="PG2"; price=3500000;
                                }
                     else
                     if(mindex==0){
                         model="PG3"; price=3400000;
                                }
        }
              String id1=JOptionPane.showInputDialog(this, "Please Enter your id number");
                  int id=Integer.parseInt(id1);
                try{
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
            Statement stmt=con.createStatement();

             String query="select id from sign_up;";
            ResultSet rs=stmt.executeQuery(query);
           while(rs.next()){
                   if(id==rs.getInt("id")){
            String query1="insert into recycle values('"+model+"',"+price+",'"+"Car"+"',"+id+");";
            int rs1=stmt.executeUpdate(query1);
            new Order().setVisible(true);
                   }
                   else
                   {JOptionPane.showMessageDialog(this, "No account exist with this ID");}
           }

            con.close();
            stmt.close();
        }
        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        

    }//GEN-LAST:event_jBuy_LMouseClicked

    private void jBMW_CBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jBMW_CBPropertyChange
        // TODO add your handling code here:
       jBMW_CB.setEditable(false);

    }//GEN-LAST:event_jBMW_CBPropertyChange

    private void jBMW_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMW_BTActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(0);
         jData_TA.setText("Information\n you have chosen BMW Cars");
        int index=jBMW_CB.getSelectedIndex();
        if(index==0){
            jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bicar_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bicar_4.jpg"));
         jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bicar_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bicar_2.jpg"));
        }
        else
            if(index==1){
                jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bxcar_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bxcar_4.jpg"));
        jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bxcar_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bxcar_2.jpg"));
            }
            else
                if(index==2){
        
        jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bgcar_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bgcar_4.jpg"));
        jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bgcar_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bgcar_2.jpg"));

                }
                else{
                     jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backcar.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\backcar.jpg"));
         jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\backcar.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\backcar.jpg"));}
    }//GEN-LAST:event_jBMW_BTActionPerformed

    private void jData_TAPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jData_TAPropertyChange
        // TODO add your handling code here:
        jData_TA.setEditable(false);
        
    }//GEN-LAST:event_jData_TAPropertyChange

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jLykan_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLykan_BTActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(1);
        jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\lcar_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\lcar_4.jpg"));
         jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\lcar_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\lcar_2.jpg"));
          jData_TA.setText("Information\n you have chosen Lykan Hypersports cars");

}//GEN-LAST:event_jLykan_BTActionPerformed

    private void jPagani_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagani_BTActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(2);
        jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\pcar_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\pcar_4.jpg"));
         jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\pcar_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\pcar_2.jpg"));
          jData_TA.setText("Information\n you have chosen Pagani Cars");
    }//GEN-LAST:event_jPagani_BTActionPerformed

    private void jImage2_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage2_LMouseClicked
        // TODO add your handling code here:
        jModel_CB.setSelectedIndex(0);
        int index=jBMW_CB.getSelectedIndex();
if(jComboBox1.getSelectedIndex()==0){
            if(index==0){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bicar_2.jpg"));
          jData_TA.setText("BMW\n Max Speed:  455kmph\nAverage:  65kmpl\nModelno:  BI1");
                         }
             else
                  if(index==1){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bxcar_2.jpg"));
          jData_TA.setText("BMW\n Max Speed:  435kmph\nAverage:  65kmpl\nModelno:  BX1");
                              }
             if(index==2){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bgcar_2.jpg"));
          jData_TA.setText("BMW\n Max Speed:  325kmph\nAverage:  65kmpl\nModelno:  BG1");
                          }
       }
else
      if(jComboBox1.getSelectedIndex()==1){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\lcar_2.jpg"));
          jData_TA.setText("Lykan Hypersports\n Max Speed:  455kmph\nAverage:  56kmpl\nModelno:  LK1");
          
                                           }
 else
      if(jComboBox1.getSelectedIndex()==2){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\pcar_2.jpg"));
          jData_TA.setText("Pagani\n Max Speed:  493kmph\nAverage:  56kmpl\nModelno:  PG1");
              }
 else

          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backcar.jpg"));
    }//GEN-LAST:event_jImage2_LMouseClicked

    private void jImage3_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage3_LMouseClicked
        // TODO add your handling code here:
         jModel_CB.setSelectedIndex(1);
        int index=jBMW_CB.getSelectedIndex();
if(jComboBox1.getSelectedIndex()==0){
            if(index==0){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bicar_3.jpg"));
          jData_TA.setText("BMW\n Max Speed:  469kmph\nAverage:  57kmpl\nModelno:  BI1");
                         }
             else
                  if(index==1){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bxcar_3.jpg"));
          jData_TA.setText("Mercedes\n Max Speed:  383kmph\nAverage:  58kmpl\nModelno:  BX1");
                    
                  }
             if(index==2){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bgcar_3.jpg"));
          jData_TA.setText("Mercedes\n Max Speed:  382kmph\nAverage:  59kmpl\nModelno:  BG1");
                          }
       }
else
          if(jComboBox1.getSelectedIndex()==1){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\lcar_3.jpg"));
          jData_TA.setText("Lykan Hypersports\n Max Speed:  469kmph\nAverage:  46kmpl\nModelno:  LK2");
                                           }
          else
              if(jComboBox1.getSelectedIndex()==2){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\pcar_3.jpg"));
          jData_TA.setText("Pagani\n Max Speed:  468kmph\nAverage:  45kmpl\nModelno:  PG2");
              }
          else

          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backcar.jpg"));
    }//GEN-LAST:event_jImage3_LMouseClicked

    private void jImage4_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage4_LMouseClicked
        // TODO add your handling code here:
         jModel_CB.setSelectedIndex(2);
        int index=jBMW_CB.getSelectedIndex();
if(jComboBox1.getSelectedIndex()==0){
            if(index==0){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bicar_4.jpg"));
          jData_TA.setText("BMW\n Max Speed:  456kmph\nAverage:  56kmpl\nModelno:  BI1");
                         }
             else
                  if(index==1){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bxcar_4.jpg"));
          jData_TA.setText("BMW\n Max Speed:  457kmph\nAverage:  57kmpl\nModelno:  BX1");
                
                  }
             if(index==2){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bgcar_4.jpg"));
          jData_TA.setText("BMW\n Max Speed:  458kmph\nAverage:  58kmpl\nModelno:  BG1");
                          }
       }
else
          if(jComboBox1.getSelectedIndex()==1){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\lcar_4.jpg"));
          jData_TA.setText("Lykan Hypersports: Logo");
                                           }
          else
              if(jComboBox1.getSelectedIndex()==2){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\pcar_4.jpg"));
          jData_TA.setText("Pagani: Logo");
              }
          else

          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backcar.jpg"));
    }//GEN-LAST:event_jImage4_LMouseClicked

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:
        jComboBox1.setVisible(false);
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jModel_CBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jModel_CBPropertyChange
        // TODO add your handling code here:
        jModel_CB.setVisible(false);
}//GEN-LAST:event_jModel_CBPropertyChange

    private void jBack_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseClicked
        // TODO add your handling code here:
        new Vehicle().setVisible(true);
        dispose();
}//GEN-LAST:event_jBack_LMouseClicked

    private void jBack_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseEntered
        // TODO add your handling code here:
        jBack_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jBack_LMouseEntered

    private void jBMW_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMW_BTMouseEntered
        // TODO add your handling code here:
        jBMW_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBMW_BTMouseEntered

    private void jLykan_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLykan_BTMouseEntered
        // TODO add your handling code here:
        jLykan_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLykan_BTMouseEntered

    private void jPagani_BTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPagani_BTMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPagani_BTMouseClicked

    private void jPagani_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPagani_BTMouseEntered
        // TODO add your handling code here:
        jPagani_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPagani_BTMouseEntered

    private void jImage2_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage2_LMouseEntered
        // TODO add your handling code here:
        jImage2_L.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_jImage2_LMouseEntered

    private void jImage3_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage3_LMouseEntered
        // TODO add your handling code here:
        jImage3_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jImage3_LMouseEntered

    private void jImage4_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage4_LMouseEntered
        // TODO add your handling code here:
        jImage4_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jImage4_LMouseEntered

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMW_BT;
    private javax.swing.JComboBox jBMW_CB;
    private javax.swing.JLabel jBack_L;
    private javax.swing.JLabel jBuy_L;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextArea jData_TA;
    private javax.swing.JLabel jImage1_L;
    private javax.swing.JLabel jImage2_L;
    private javax.swing.JLabel jImage3_L;
    private javax.swing.JLabel jImage4_L;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLykan_BT;
    private javax.swing.JComboBox jModel_CB;
    private javax.swing.JButton jPagani_BT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
