/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * First_Window.java
 *
 * Created on 10 Dec, 2018, 5:14:27 PM
 */

package cars;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Cursor;

/**
 *
 * @author DEll
 */
public class First_Window extends javax.swing.JFrame {

    /** Creates new form First_Window */
    public First_Window() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSign_up_L = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jForgot_Password_L = new javax.swing.JLabel();
        jLogin_FR = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLogin_BT = new javax.swing.JLabel();
        jName_TF = new javax.swing.JTextField();
        jPassword_F = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLogin_L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        getContentPane().setLayout(null);

        jSign_up_L.setFont(new java.awt.Font("Calisto MT", 1, 18));
        jSign_up_L.setForeground(new java.awt.Color(255, 255, 255));
        jSign_up_L.setText("<html> <head> <u> Sign up</u> </head> </html>");
        jSign_up_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSign_up_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSign_up_LMouseEntered(evt);
            }
        });
        getContentPane().add(jSign_up_L);
        jSign_up_L.setBounds(30, 280, 70, 20);

        jLabel5.setBackground(new java.awt.Color(204, 255, 255));
        jLabel5.setFont(new java.awt.Font("Nyala", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tech Motors");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 0, 220, 40);

        jForgot_Password_L.setFont(new java.awt.Font("Cambria", 1, 18));
        jForgot_Password_L.setForeground(new java.awt.Color(0, 153, 153));
        jForgot_Password_L.setText("<html><head><u>Forgot Password</u></head></html>");
        jForgot_Password_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jForgot_Password_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jForgot_Password_LMouseEntered(evt);
            }
        });
        getContentPane().add(jForgot_Password_L);
        jForgot_Password_L.setBounds(10, 300, 140, 20);

        jLogin_FR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLogin_FR.setFrameIcon(null);
        jLogin_FR.setVisible(true);
        jLogin_FR.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLogin_FRPropertyChange(evt);
            }
        });
        jLogin_FR.getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log-In", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Cambria", 0, 36), new java.awt.Color(204, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jExit.setFont(new java.awt.Font("Tahoma", 1, 14));
        jExit.setForeground(new java.awt.Color(153, 0, 0));
        jExit.setText("Exit");
        jExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitMouseClicked(evt);
            }
        });
        jExit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jExitPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("User Name");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Password");

        jLogin_BT.setFont(new java.awt.Font("Nyala", 1, 18));
        jLogin_BT.setForeground(new java.awt.Color(153, 255, 204));
        jLogin_BT.setText("Log-In");
        jLogin_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogin_BTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLogin_BTMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPassword_F, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jName_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLogin_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword_F, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLogin_BT)
                .addGap(29, 29, 29)
                .addComponent(jExit, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
        );

        jLogin_FR.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 232);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/button.jpg"))); // NOI18N
        jLogin_FR.getContentPane().add(jLabel4);
        jLabel4.setBounds(-300, -70, 850, 440);

        getContentPane().add(jLogin_FR);
        jLogin_FR.setBounds(170, 50, 320, 270);

        jLogin_L.setBackground(new java.awt.Color(0, 0, 255));
        jLogin_L.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jLogin_L.setForeground(new java.awt.Color(255, 255, 255));
        jLogin_L.setText("<html><head><u>Log_In</u></head></html>");
        jLogin_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogin_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLogin_LMouseEntered(evt);
            }
        });
        getContentPane().add(jLogin_L);
        jLogin_L.setBounds(10, 0, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/abstraction_light_neon_glitter_97687_1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 650, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSign_up_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSign_up_LMouseClicked
        // TODO add your handling code here:
        new Sign_up().setVisible(true);
        dispose();
}//GEN-LAST:event_jSign_up_LMouseClicked

    private void jSign_up_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSign_up_LMouseEntered
        // TODO add your handling code here:
        jSign_up_L.setCursor(new Cursor(Cursor.HAND_CURSOR));

}//GEN-LAST:event_jSign_up_LMouseEntered

    private void jForgot_Password_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jForgot_Password_LMouseEntered
        // TODO add your handling code here:
        jForgot_Password_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jForgot_Password_LMouseEntered

    private void jForgot_Password_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jForgot_Password_LMouseClicked
        // TODO add your handling code here:
        new Forgot_Password().setVisible(true);
        dispose();
}//GEN-LAST:event_jForgot_Password_LMouseClicked

    private void jLogin_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogin_BTMouseEntered
        // TODO add your handling code here:
        jLogin_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jLogin_BTMouseEntered

    private void jLogin_BTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogin_BTMouseClicked
        // TODO add your handling code here:
        String name=jName_TF.getText();
        String password=new String(jPassword_F.getPassword());
        try{
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
            Statement stmt=con.createStatement();

            String query="select* from sign_up;";
            ResultSet rs=stmt.executeQuery(query);

            while(rs.next()){
                if(name.equals(rs.getString("name"))){
                    if(password.equals(rs.getString("password"))){
                      JOptionPane.showMessageDialog(this, "Welcome to Motor Tech");
                       new Vehicle().setVisible(true);
                        dispose();
                    }
                    else
                    {JOptionPane.showMessageDialog(this, "You have typed incorrect password");}
                }
                else
                {JOptionPane.showMessageDialog(this, "You have typed incorrect username");}
            }
            con.close();
            stmt.close();
            rs.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
       
}//GEN-LAST:event_jLogin_BTMouseClicked

    private void jLogin_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogin_LMouseClicked
        // TODO add your handling code here:
        jLogin_FR.setVisible(true);

    }//GEN-LAST:event_jLogin_LMouseClicked

    private void jLogin_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogin_LMouseEntered
        // TODO add your handling code here:
        jLogin_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
    }//GEN-LAST:event_jLogin_LMouseEntered

    private void jLogin_FRPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLogin_FRPropertyChange
        // TODO add your handling code here:
        jLogin_FR.setVisible(false);

    }//GEN-LAST:event_jLogin_FRPropertyChange

    private void jExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseClicked
        // TODO add your handling code here:
        jLogin_FR.setVisible(false);
}//GEN-LAST:event_jExitMouseClicked

    private void jExitPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jExitPropertyChange
        // TODO add your handling code here:
        jExit.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jExitPropertyChange

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jExit;
    private javax.swing.JLabel jForgot_Password_L;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLogin_BT;
    private javax.swing.JInternalFrame jLogin_FR;
    private javax.swing.JLabel jLogin_L;
    private javax.swing.JTextField jName_TF;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword_F;
    private javax.swing.JLabel jSign_up_L;
    // End of variables declaration//GEN-END:variables

}
