/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Forgot_Password.java
 *
 * Created on 11 Dec, 2018, 6:27:52 AM
 */

package cars;
import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
/**
 *
 * @author DEll
 */
public class Forgot_Password extends javax.swing.JFrame {

    /** Creates new form Forgot_Password */
    public Forgot_Password() {
        initComponents();
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPhone_TF = new javax.swing.JTextField();
        jContinue_BT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jOtp_BT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jOtp_TF = new javax.swing.JTextField();
        jCheck_BT = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jBack_L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Enter Your Phone Number");

        jPhone_TF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPhone_TF.setForeground(new java.awt.Color(255, 255, 255));
        jPhone_TF.setOpaque(false);

        jContinue_BT.setBackground(new java.awt.Color(204, 255, 204));
        jContinue_BT.setFont(new java.awt.Font("Nyala", 0, 24)); // NOI18N
        jContinue_BT.setText("Continue");
        jContinue_BT.setOpaque(false);
        jContinue_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jContinue_BTMouseEntered(evt);
            }
        });
        jContinue_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContinue_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPhone_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jContinue_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhone_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jContinue_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 100, 597, 116);

        jLabel4.setFont(new java.awt.Font("Nyala", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("RESET YOUR PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 40, 453, 47);

        jOtp_BT.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jOtp_BT.setText("Send OTP to Phone Number");
        jOtp_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jOtp_BTMouseEntered(evt);
            }
        });
        jOtp_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOtp_BTActionPerformed(evt);
            }
        });
        getContentPane().add(jOtp_BT);
        jOtp_BT.setBounds(120, 270, 270, 33);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setText("OR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 240, 18, 18);

        jOtp_TF.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jOtp_TFPropertyChange(evt);
            }
        });
        getContentPane().add(jOtp_TF);
        jOtp_TF.setBounds(120, 320, 90, 20);

        jCheck_BT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheck_BT.setText("Check OTP");
        jCheck_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheck_BTMouseEntered(evt);
            }
        });
        jCheck_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck_BTActionPerformed(evt);
            }
        });
        jCheck_BT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCheck_BTPropertyChange(evt);
            }
        });
        getContentPane().add(jCheck_BT);
        jCheck_BT.setBounds(233, 320, 110, 23);

        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(420, 270, 110, 30);

        jBack_L.setBackground(new java.awt.Color(255, 255, 255));
        jBack_L.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jBack_L.setForeground(new java.awt.Color(51, 0, 51));
        jBack_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/back.png"))); // NOI18N
        jBack_L.setText("Back");
        jBack_L.setOpaque(true);
        jBack_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBack_LMouseEntered(evt);
            }
        });
        getContentPane().add(jBack_L);
        jBack_L.setBounds(0, 0, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/the_witcher_3_wild_hunt_the_witcher_cd_projekt_99850_1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-110, -10, 940, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jContinue_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContinue_BTActionPerformed
        // TODO add your handling code here:
        int pno=Integer.parseInt(jPhone_TF.getText());
    

        try{
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
                 Statement stmt=con.createStatement();
                 
                 String query="select * from sign_up;";
            ResultSet rs=stmt.executeQuery(query);
    while(rs.next()){
            if(pno==(rs.getInt("phone_no"))){
           
                String s_password=JOptionPane.showInputDialog(this,"Enter your new password");
                
                String query1="update sign_up set password='"+s_password+"' where phone_no="+pno+";";
                int  rs1=stmt.executeUpdate(query1);
                JOptionPane.showMessageDialog(this,"Your password has successfully been recovered");

            }
            else
            {JOptionPane.showMessageDialog(this,"This number doesn't contain any account");}

       }
            
            con.close();
            stmt.close();
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
}//GEN-LAST:event_jContinue_BTActionPerformed

    private void jOtp_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOtp_BTActionPerformed
        // TODO add your handling code here:
             jCheck_BT.setVisible(true);
             jOtp_TF.setVisible(true);
        String pno1=JOptionPane.showInputDialog(this,"Please enter your mobile number");
        int pno=Integer.parseInt(pno1);
        jTextField1.setText(""+pno);
        try{
        Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
                 Statement stmt=con.createStatement();
                 String query="select* from sign_up;";
                 ResultSet rs=stmt.executeQuery(query);

        while(rs.next()){
            if(pno==rs.getInt("phone_no")){

                  String query1="select* from otp;";
                  ResultSet rs1=stmt.executeQuery(query1);
                  int otp=0;
                  while(rs1.next()){
                      otp=rs1.getInt("otp");
                     }
                  otp++;
                  String query2="insert into otp values("+otp+");";
                  int rs2=stmt.executeUpdate(query2);
                  JOptionPane.showMessageDialog(this, "Your OTP is  "+otp);
                     }
              else
              {JOptionPane.showMessageDialog(this,"This number doesn't contain any account");}
        }
                 con.close();
                 stmt.close();
                 rs.close();

                 }
         catch(Exception e){
             JOptionPane.showMessageDialog(this, e.getMessage());
         }
}//GEN-LAST:event_jOtp_BTActionPerformed

    private void jOtp_TFPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jOtp_TFPropertyChange
        // TODO add your handling code here:
        jOtp_TF.setVisible(false);
        
    }//GEN-LAST:event_jOtp_TFPropertyChange

    private void jCheck_BTPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCheck_BTPropertyChange
        // TODO add your handling code here:
        jCheck_BT.setVisible(false);

}//GEN-LAST:event_jCheck_BTPropertyChange

    private void jCheck_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck_BTActionPerformed
        // TODO add your handling code here:
        int otp=Integer.parseInt(jOtp_TF.getText());
        int pno=Integer.parseInt(jTextField1.getText());

            try{
                Class.forName("java.sql.Driver");
                Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
                 Statement stmt=con.createStatement();
                 String query="select* from otp;";
                 ResultSet rs=stmt.executeQuery(query);
                 rs.last();
                // while(rs.next()){
                     if(otp==rs.getInt("otp")){
                         String s_password=JOptionPane.showInputDialog(this,"Enter your new password");

                String query1="update sign_up set password='"+s_password+"' where phone_no="+pno+";";
                int  rs1=stmt.executeUpdate(query1);
                JOptionPane.showMessageDialog(this,"Your password has successfully been recovered");
                     }
                     else
                     { JOptionPane.showMessageDialog(this,"Your OTP doesn't match");}
                
                 con.close();
                 stmt.close();
                 rs.close();
        } catch(Exception e){
             JOptionPane.showMessageDialog(this, e.getMessage());
         }
    }//GEN-LAST:event_jCheck_BTActionPerformed

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
        // TODO add your handling code here:
        jTextField1.setVisible(false);

    }//GEN-LAST:event_jTextField1PropertyChange

    private void jBack_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseClicked
        // TODO add your handling code here:
        new First_Window().setVisible(true);
        dispose();
}//GEN-LAST:event_jBack_LMouseClicked

    private void jBack_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseEntered
        // TODO add your handling code here:
        jBack_L.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_jBack_LMouseEntered

    private void jContinue_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jContinue_BTMouseEntered
        // TODO add your handling code here:
         jContinue_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jContinue_BTMouseEntered

    private void jOtp_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOtp_BTMouseEntered
        // TODO add your handling code here:
          jOtp_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jOtp_BTMouseEntered

    private void jCheck_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheck_BTMouseEntered
        // TODO add your handling code here:
        jCheck_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jCheck_BTMouseEntered

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBack_L;
    private javax.swing.JButton jCheck_BT;
    private javax.swing.JButton jContinue_BT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jOtp_BT;
    private javax.swing.JTextField jOtp_TF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPhone_TF;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
