/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Jet.java
 *
 * Created on 11 Dec, 2018, 6:26:30 AM
 */

package cars;
import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author DEll
 */
public class Jet extends javax.swing.JFrame {

    /** Creates new form Jet */
    public Jet() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jData_TA = new javax.swing.JTextArea();
        jCessna_BT = new javax.swing.JButton();
        jBeech_BT = new javax.swing.JButton();
        jBuy_BT = new javax.swing.JLabel();
        jAvanti_BT = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jModel_CB = new javax.swing.JComboBox();
        jImage1_L = new javax.swing.JLabel();
        jImage2_L = new javax.swing.JLabel();
        jImage3_L = new javax.swing.JLabel();
        jImage4_L = new javax.swing.JLabel();
        jBack_L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nyala", 0, 36));
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Private Jets");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 0, 210, 40);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jData_TA.setColumns(20);
        jData_TA.setRows(5);
        jScrollPane1.setViewportView(jData_TA);

        jCessna_BT.setFont(new java.awt.Font("Century", 0, 14));
        jCessna_BT.setText("Cessna-Citation");
        jCessna_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCessna_BTMouseEntered(evt);
            }
        });
        jCessna_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCessna_BTActionPerformed(evt);
            }
        });

        jBeech_BT.setFont(new java.awt.Font("Century", 0, 14));
        jBeech_BT.setText("Beech");
        jBeech_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBeech_BTMouseEntered(evt);
            }
        });
        jBeech_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeech_BTActionPerformed(evt);
            }
        });

        jBuy_BT.setFont(new java.awt.Font("Century", 0, 18));
        jBuy_BT.setForeground(new java.awt.Color(204, 255, 255));
        jBuy_BT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBuy_BT.setText("Buy Now");
        jBuy_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuy_BTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBuy_BTMouseEntered(evt);
            }
        });

        jAvanti_BT.setFont(new java.awt.Font("Century", 0, 14));
        jAvanti_BT.setText("Avanti");
        jAvanti_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAvanti_BTMouseEntered(evt);
            }
        });
        jAvanti_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAvanti_BTActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });

        jModel_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jModel_CB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jModel_CBPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBuy_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCessna_BT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jAvanti_BT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jBeech_BT, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jModel_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCessna_BT)
                .addGap(18, 18, 18)
                .addComponent(jBeech_BT)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAvanti_BT)
                    .addComponent(jModel_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBuy_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jImage1_L.setBackground(new java.awt.Color(0, 0, 0));
        jImage1_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/vq-bmt-private-gulfstream-aerospace-g-iv-gulfstream-iv_PlanespottersNet_823146_161ad4c6e9.jpg"))); // NOI18N
        jImage1_L.setOpaque(true);

        jImage2_L.setBackground(new java.awt.Color(0, 0, 0));
        jImage2_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/download (3).jpg"))); // NOI18N
        jImage2_L.setOpaque(true);
        jImage2_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage2_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage2_LMouseEntered(evt);
            }
        });

        jImage3_L.setBackground(new java.awt.Color(0, 0, 0));
        jImage3_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/images (1).jpg"))); // NOI18N
        jImage3_L.setOpaque(true);
        jImage3_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage3_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage3_LMouseEntered(evt);
            }
        });

        jImage4_L.setBackground(new java.awt.Color(0, 0, 0));
        jImage4_L.setOpaque(true);
        jImage4_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage4_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImage4_LMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jImage1_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jImage4_L, 0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jImage2_L, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jImage3_L, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jImage1_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jImage2_L, 0, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jImage3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jImage4_L)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 50, 970, 330);

        jBack_L.setBackground(new java.awt.Color(255, 255, 255));
        jBack_L.setFont(new java.awt.Font("Nyala", 0, 18));
        jBack_L.setForeground(new java.awt.Color(51, 0, 51));
        jBack_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/back.png"))); // NOI18N
        jBack_L.setText("Back");
        jBack_L.setOpaque(true);
        jBack_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBack_LMouseEntered(evt);
            }
        });
        getContentPane().add(jBack_L);
        jBack_L.setBounds(0, 0, 70, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 70, 750, 340);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/radiation_sign_spot_86968_1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -10, 1040, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCessna_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCessna_BTActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(0);
        jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\cjet_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\cjet_4.jpg"));
         jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\cjet_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\cjet_2.jpg"));
          jData_TA.setText("Information\n you have chosen Cessna-Citation Jets");
}//GEN-LAST:event_jCessna_BTActionPerformed

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:
        jComboBox1.setVisible(false);
        
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jBeech_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeech_BTActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(1);
        jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bjet_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bjet_4.jpg"));
         jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bjet_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\bjet_2.jpg"));
          jData_TA.setText("Information\n you have chosen Beech Jets");
    }//GEN-LAST:event_jBeech_BTActionPerformed

    private void jAvanti_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAvanti_BTActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(2);
        jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\ajet_2.jpg"));
        jImage4_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\ajet_4.jpg"));
         jImage3_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\ajet_3.jpg"));
          jImage2_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\s\\ajet_2.jpg"));
          jData_TA.setText("Information\n you have chosen Avanti Jets");
    }//GEN-LAST:event_jAvanti_BTActionPerformed

    private void jImage2_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage2_LMouseClicked
        // TODO add your handling code here:
        jModel_CB.setSelectedIndex(0);
         if(jComboBox1.getSelectedIndex()==0){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\cjet_2.jpg"));
          jData_TA.setText("Cessna-Citation \n Max Speed:  988kmph\nAverage:  120kmpl\nModelno:  C1");
      }
      else
          if(jComboBox1.getSelectedIndex()==1){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bjet_2.jpg"));
          jData_TA.setText("Beech\n Max Speed:  967kmph\nAverage:  130kmpl\nModelno:  B1");
      }
          else
       if(jComboBox1.getSelectedIndex()==2){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\ajet_2.jpg"));
          jData_TA.setText("Avanti \n Max Speed:  856kmph\nAverage:  140kmpl\nModelno:  A1");
                              }
       else
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backjet.jpg"));
    }//GEN-LAST:event_jImage2_LMouseClicked

    private void jImage3_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage3_LMouseClicked
        // TODO add your handling code here:
        jModel_CB.setSelectedIndex(1);
        if(jComboBox1.getSelectedIndex()==0){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\cjet_3.jpg"));
          jData_TA.setText("Cessna-Citation \n Max Speed:  989kmph\nAverage:  121kmpl\nModelno:  C2");
      }
      else
          if(jComboBox1.getSelectedIndex()==1){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bjet_3.jpg"));
          jData_TA.setText("Beech\n Max Speed:  968kmph\nAverage:  131kmpl\nModelno:  B2");
      }
          else
       if(jComboBox1.getSelectedIndex()==2){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\ajet_3.jpg"));
          jData_TA.setText("Avanti \n Max Speed:  857kmph\nAverage:  141kmpl\nModelno:  A2");
                              }
       else
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backjet.jpg"));
    }//GEN-LAST:event_jImage3_LMouseClicked

    private void jImage4_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage4_LMouseClicked
        // TODO add your handling code here:
        jModel_CB.setSelectedIndex(2);
         if(jComboBox1.getSelectedIndex()==0){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\cjet_4.jpg"));
          jData_TA.setText("Cessna-Citation \n Max Speed:  990kmph\nAverage:  122kmpl\nModelno:  C3");
      }
      else
          if(jComboBox1.getSelectedIndex()==1){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\bjet_4.jpg"));
          jData_TA.setText("Beech\n Max Speed:  969kmph\nAverage:  132kmpl\nModelno:  B3");
      }
          else
       if(jComboBox1.getSelectedIndex()==2){
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\ajet_4.jpg"));
          jData_TA.setText("Avanti \n Max Speed:  858kmph\nAverage:  142kmpl\nModelno:  A3");
                              }
       else
          jImage1_L.setIcon(new ImageIcon("F:\\Apps\\k\\a\\backjet.jpg"));
    }//GEN-LAST:event_jImage4_LMouseClicked

    private void jBuy_BTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuy_BTMouseClicked
        // TODO add your handling code here:
        try{
        String model="a";
        int price=0;
        int index1=jComboBox1.getSelectedIndex();
        int mindex=jModel_CB.getSelectedIndex();
        if(index1==0){
                     if(mindex==0){
                         model="C1"; price=6000000;
                                }
                     else
                     if(mindex==1){
                         model="C2"; price=5000000;
                                }
                     else
                     if(mindex==2){
                         model="C3"; price=4000000;
                                }
        }
         else
         if(index1==1){
                     if(mindex==0){
                         model="B1"; price=5000000;
                                }
                     else
                     if(mindex==1){
                         model="B2"; price=6000000;
                                }
                     else
                     if(mindex==2){
                         model="B3"; price=4500000;
                                }
                       }
        else
         if(index1==2){
                     if(mindex==0){
                         model="A1"; price=500000;
                                }
                     else
                     if(mindex==1){
                         model="A2"; price=600000;
                                }
                     else
                     if(mindex==2){
                         model="A3"; price=450000;
                                }
                       }
               String id1=JOptionPane.showInputDialog(this, "Please Enter your id number");
                  int id=Integer.parseInt(id1);

         Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
            Statement stmt=con.createStatement();

             String query="select id from sign_up;";
            ResultSet rs=stmt.executeQuery(query);

            while(rs.next()){
                   if(id==rs.getInt("id")){
            String query1="insert into recycle values('"+model+"',"+price+",'"+"Jet"+"',"+id+");";
            int rs1=stmt.executeUpdate(query1);
             new Order().setVisible(true);
                   }
                   else
                   { JOptionPane.showMessageDialog(this, "No account exist with this ID");}
            }
             
            con.close();
            stmt.close();
        }
        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

       

    }//GEN-LAST:event_jBuy_BTMouseClicked

    private void jModel_CBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jModel_CBPropertyChange
        // TODO add your handling code here:
        jModel_CB.setVisible(false);

    }//GEN-LAST:event_jModel_CBPropertyChange

    private void jBack_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseClicked
        // TODO add your handling code here:
      new Vehicle().setVisible(true);
         dispose();
}//GEN-LAST:event_jBack_LMouseClicked

    private void jBack_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseEntered
        // TODO add your handling code here:
        jBack_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jBack_LMouseEntered

    private void jCessna_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCessna_BTMouseEntered
        // TODO add your handling code here:
        jCessna_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jCessna_BTMouseEntered

    private void jBeech_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBeech_BTMouseEntered
        // TODO add your handling code here:
        jBeech_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBeech_BTMouseEntered

    private void jAvanti_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAvanti_BTMouseEntered
        // TODO add your handling code here:
        jAvanti_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jAvanti_BTMouseEntered

    private void jBuy_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuy_BTMouseEntered
        // TODO add your handling code here:
        jBuy_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBuy_BTMouseEntered

    private void jImage2_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage2_LMouseEntered
        // TODO add your handling code here:
        jImage2_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jImage2_LMouseEntered

    private void jImage3_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage3_LMouseEntered
        // TODO add your handling code here:
         jImage3_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jImage3_LMouseEntered

    private void jImage4_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage4_LMouseEntered
        // TODO add your handling code here:
        jImage4_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jImage4_LMouseEntered

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAvanti_BT;
    private javax.swing.JLabel jBack_L;
    private javax.swing.JButton jBeech_BT;
    private javax.swing.JLabel jBuy_BT;
    private javax.swing.JButton jCessna_BT;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextArea jData_TA;
    private javax.swing.JLabel jImage1_L;
    private javax.swing.JLabel jImage2_L;
    private javax.swing.JLabel jImage3_L;
    private javax.swing.JLabel jImage4_L;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox jModel_CB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
