/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Payment.java
 *
 * Created on 11 Dec, 2018, 6:27:24 AM
 */

package cars;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author DEll
 */
public class Payment extends javax.swing.JFrame {

    /** Creates new form Payment */
    public Payment() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCredit_L = new javax.swing.JLabel();
        jDebit_L = new javax.swing.JLabel();
        jCVV_P = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCvv_TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPay_L = new javax.swing.JLabel();
        jPin_TF = new javax.swing.JPasswordField();
        jBack_L = new javax.swing.JLabel();
        jRegister_BT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nyala", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("  PAYMENT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 262, 50);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pay", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 18))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jCredit_L.setBackground(new java.awt.Color(255, 153, 51));
        jCredit_L.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jCredit_L.setForeground(new java.awt.Color(255, 255, 255));
        jCredit_L.setText("Credit Card");
        jCredit_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCredit_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCredit_LMouseEntered(evt);
            }
        });

        jDebit_L.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jDebit_L.setForeground(new java.awt.Color(255, 255, 255));
        jDebit_L.setText("Debit Card");
        jDebit_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDebit_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDebit_LMouseEntered(evt);
            }
        });

        jCVV_P.setBackground(new java.awt.Color(0, 102, 102));
        jCVV_P.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCVV_PPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Enter your CVV");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Enter your PIN");

        jPay_L.setBackground(new java.awt.Color(51, 102, 0));
        jPay_L.setFont(new java.awt.Font("Nyala", 0, 24));
        jPay_L.setForeground(new java.awt.Color(102, 255, 255));
        jPay_L.setText("Pay");
        jPay_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPay_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPay_LMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jCVV_PLayout = new javax.swing.GroupLayout(jCVV_P);
        jCVV_P.setLayout(jCVV_PLayout);
        jCVV_PLayout.setHorizontalGroup(
            jCVV_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCVV_PLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jCVV_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPay_L, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jCVV_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPin_TF)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(jCvv_TF)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jCVV_PLayout.setVerticalGroup(
            jCVV_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCVV_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCvv_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPin_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPay_L, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDebit_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCredit_L, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCVV_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jCredit_L, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDebit_L, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCVV_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 70, 390, 274);

        jBack_L.setBackground(new java.awt.Color(255, 255, 255));
        jBack_L.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jBack_L.setForeground(new java.awt.Color(51, 0, 51));
        jBack_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/back.png"))); // NOI18N
        jBack_L.setText("Back");
        jBack_L.setOpaque(true);
        jBack_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBack_LMouseEntered(evt);
            }
        });
        getContentPane().add(jBack_L);
        jBack_L.setBounds(0, 0, 70, 30);

        jRegister_BT.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRegister_BT.setText("Get Registered");
        jRegister_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jRegister_BTMouseEntered(evt);
            }
        });
        jRegister_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegister_BTActionPerformed(evt);
            }
        });
        getContentPane().add(jRegister_BT);
        jRegister_BT.setBounds(390, 40, 130, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/OnlineBanking_CyberImage_CaseStudy.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 540, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCVV_PPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCVV_PPropertyChange
        // TODO add your handling code here:
        jCVV_P.setVisible(false);
}//GEN-LAST:event_jCVV_PPropertyChange

    private void jCredit_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCredit_LMouseClicked
        // TODO add your handling code here:
        jCVV_P.setVisible(true);
}//GEN-LAST:event_jCredit_LMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jCVV_P.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        jCVV_P.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void jDebit_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDebit_LMouseClicked
        // TODO add your handling code here:
        jCVV_P.setVisible(true);
}//GEN-LAST:event_jDebit_LMouseClicked

    private void jRegister_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegister_BTActionPerformed
        // TODO add your handling code here:
        new Internet_Banking().setVisible(true);
        dispose();
}//GEN-LAST:event_jRegister_BTActionPerformed

    private void jPay_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPay_LMouseClicked
        // TODO add your handling code here:
       int  cvv=Integer.parseInt(jCvv_TF.getText());
       String pin1=new String(jPin_TF.getPassword());
       int pin=Integer.parseInt(pin1);

      try{
          Class.forName("java.sql.Driver");
          Connection con=(Connection)DriverManager.getConnection
                  ("jdbc:mysql://localhost:3306/cars","root","");
          Statement stmt=con.createStatement();

          String query="select* from recycle;";
          ResultSet rs=stmt.executeQuery(query);
          rs.last();
             String model=rs.getString("model");
             String vehicle=rs.getString("vehicle");
             int price=rs.getInt("price");
             int id=rs.getInt("id");

          String query1="select* from internet_banking;";
          ResultSet rs1=stmt.executeQuery(query1);

  while(rs1.next()){
     if(id==rs1.getInt("id")){
           if(cvv==rs1.getInt("cvv")){
               if(pin==rs1.getInt("pin")){
                       
String query2="insert into orders values('"+vehicle+"','"+model+"',"+null+","+"1"+","+price+","+id+");";
                      int rs2=stmt.executeUpdate(query2);
            JOptionPane.showMessageDialog(this, "You have successfully paid your bill");
            new Purchased().setVisible(true);
            dispose();
            }
               else
               {JOptionPane.showMessageDialog(this, "Please enter correct Pin");}
          }
               else
               { JOptionPane.showMessageDialog(this, "Please enter correct Cvv");}
     }
           else
           { JOptionPane.showMessageDialog(this, "Incorrect CVV regard with this ID");}

     }
      

          con.close();
          stmt.close();
          rs.close();
          rs1.close();
      }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
           
             }
       
}//GEN-LAST:event_jPay_LMouseClicked

    private void jBack_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseClicked
        // TODO add your handling code here:
        new Vehicle().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBack_LMouseClicked

    private void jBack_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseEntered
        // TODO add your handling code here:
        jBack_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBack_LMouseEntered

    private void jCredit_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCredit_LMouseEntered
        // TODO add your handling code here:
        jCredit_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jCredit_LMouseEntered

    private void jDebit_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDebit_LMouseEntered
        // TODO add your handling code here:
        jDebit_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jDebit_LMouseEntered

    private void jPay_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPay_LMouseEntered
        // TODO add your handling code here:
        jPay_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPay_LMouseEntered

    private void jRegister_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegister_BTMouseEntered
        // TODO add your handling code here:
         jRegister_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jRegister_BTMouseEntered

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBack_L;
    private javax.swing.JPanel jCVV_P;
    private javax.swing.JLabel jCredit_L;
    private javax.swing.JTextField jCvv_TF;
    private javax.swing.JLabel jDebit_L;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPay_L;
    private javax.swing.JPasswordField jPin_TF;
    private javax.swing.JButton jRegister_BT;
    // End of variables declaration//GEN-END:variables

}
