/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Purchased.java
 *
 * Created on 24 Dec, 2018, 8:42:56 AM
 */

package cars;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Cursor;

/**
 *
 * @author DEll
 */
public class Purchased extends javax.swing.JFrame {

    /** Creates new form Purchased */
    public Purchased() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheck_Orders_BT = new javax.swing.JButton();
        jPurchased_L = new javax.swing.JLabel();
        jExit_L = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Congratulation", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Nyala", 0, 36), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Nyala", 0, 24));
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("You have purchased");

        jCheck_Orders_BT.setFont(new java.awt.Font("Nyala", 0, 18));
        jCheck_Orders_BT.setText("Check Orders");
        jCheck_Orders_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheck_Orders_BTMouseEntered(evt);
            }
        });
        jCheck_Orders_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck_Orders_BTActionPerformed(evt);
            }
        });

        jPurchased_L.setBackground(new java.awt.Color(255, 255, 0));
        jPurchased_L.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPurchased_L.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jCheck_Orders_BT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPurchased_L, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPurchased_L, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheck_Orders_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 60, 360, 223);

        jExit_L.setFont(new java.awt.Font("Nyala", 0, 18));
        jExit_L.setForeground(new java.awt.Color(204, 0, 0));
        jExit_L.setText("Exit");
        jExit_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExit_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExit_LMouseEntered(evt);
            }
        });
        getContentPane().add(jExit_L);
        jExit_L.setBounds(450, 10, 29, 24);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/purch.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 580, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheck_Orders_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck_Orders_BTActionPerformed
        // TODO add your handling code here:

        new Your_Orders().setVisible(true);
        dispose();
    }//GEN-LAST:event_jCheck_Orders_BTActionPerformed

    private void jExit_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit_LMouseClicked
        // TODO add your handling code here:
        new Vehicle().setVisible(true);
        dispose();
}//GEN-LAST:event_jExit_LMouseClicked

    private void jExit_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit_LMouseEntered
        // TODO add your handling code here:
        jExit_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jExit_LMouseEntered

    private void jCheck_Orders_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheck_Orders_BTMouseEntered
        // TODO add your handling code here:
         jCheck_Orders_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jCheck_Orders_BTMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
            Statement stmt=con.createStatement();
            String query="select *from orders;";

            ResultSet rs=stmt.executeQuery(query);
            rs.last();
            String model=rs.getString("model_no");
            String vehicle=rs.getString("vehicle");
            int price=rs.getInt("price");
            jPurchased_L.setText("1 "+vehicle+" with Model_no "+model+" of price Rs. "+price);

            con.close();
            stmt.close();
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchased().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCheck_Orders_BT;
    private javax.swing.JLabel jExit_L;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPurchased_L;
    // End of variables declaration//GEN-END:variables

}
