/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Vehicle.java
 *
 * Created on 10 Dec, 2018, 8:17:43 PM
 */

package cars;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import java.awt.Desktop;
import java.net.URI;



/**
 *
 * @author DEll
 */
public class Vehicle extends javax.swing.JFrame {

    /** Creates new form Vehicle */
    public Vehicle() {
        initComponents();
    }




    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jAccount_BT = new javax.swing.JButton();
        jAbout_us_BT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCars_L = new javax.swing.JLabel();
        jBike_L = new javax.swing.JLabel();
        jTruck_L = new javax.swing.JLabel();
        jJet_L = new javax.swing.JLabel();
        jLog_Out_BT = new javax.swing.JButton();
        jWebsite_L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nyala", 0, 48));
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Tech Motors");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 310, 80);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 400));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setOpaque(false);

        jAccount_BT.setFont(new java.awt.Font("Nyala", 0, 18));
        jAccount_BT.setText("My_Account");
        jAccount_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAccount_BTMouseEntered(evt);
            }
        });
        jAccount_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccount_BTActionPerformed(evt);
            }
        });

        jAbout_us_BT.setFont(new java.awt.Font("Nyala", 0, 18));
        jAbout_us_BT.setText("About_us");
        jAbout_us_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAbout_us_BTMouseEntered(evt);
            }
        });
        jAbout_us_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbout_us_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAbout_us_BT, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jAccount_BT, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jAccount_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jAbout_us_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose  Vehicle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nyala", 0, 24), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel3.setOpaque(false);

        jCars_L.setBackground(new java.awt.Color(102, 255, 255));
        jCars_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/videoblocks-animated-car-front-red-3d-icon-loop-modules-for-edit-with-alpha-matte_broxluolb_thumbnail-full07.png"))); // NOI18N
        jCars_L.setOpaque(true);
        jCars_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCars_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCars_LMouseEntered(evt);
            }
        });

        jBike_L.setBackground(new java.awt.Color(255, 153, 51));
        jBike_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/animated-motorcycle-glass-3d-icon-loop-modules-for-edit-with-alpha-matte_hpqhckca_thumbnail-full04.png"))); // NOI18N
        jBike_L.setOpaque(true);
        jBike_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBike_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBike_LMouseEntered(evt);
            }
        });

        jTruck_L.setBackground(new java.awt.Color(255, 255, 51));
        jTruck_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/8c6ogbRdi.png"))); // NOI18N
        jTruck_L.setOpaque(true);
        jTruck_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTruck_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTruck_LMouseEntered(evt);
            }
        });

        jJet_L.setBackground(new java.awt.Color(204, 204, 0));
        jJet_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/9.jpg"))); // NOI18N
        jJet_L.setOpaque(true);
        jJet_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jJet_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jJet_LMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTruck_L, 0, 0, Short.MAX_VALUE)
                    .addComponent(jCars_L, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jJet_L, 0, 0, Short.MAX_VALUE)
                    .addComponent(jBike_L, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCars_L, javax.swing.GroupLayout.PREFERRED_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jBike_L, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jJet_L, 0, 0, Short.MAX_VALUE)
                    .addComponent(jTruck_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLog_Out_BT.setFont(new java.awt.Font("Nyala", 0, 18));
        jLog_Out_BT.setText("Log_Out");
        jLog_Out_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLog_Out_BTMouseEntered(evt);
            }
        });
        jLog_Out_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog_Out_BTActionPerformed(evt);
            }
        });

        jWebsite_L.setFont(new java.awt.Font("Nyala", 0, 18));
        jWebsite_L.setForeground(new java.awt.Color(204, 255, 255));
        jWebsite_L.setText("<html><head><u>www.MotorTech.co.in</u></head></html>");
        jWebsite_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jWebsite_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jWebsite_LMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jWebsite_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLog_Out_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jWebsite_L, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLog_Out_BT)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 80, 700, 390);

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCars_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCars_LMouseClicked
        // TODO add your handling code here:
        new Car().setVisible(true);

    }//GEN-LAST:event_jCars_LMouseClicked

    private void jBike_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBike_LMouseClicked
        // TODO add your handling code here:
        new Bike().setVisible(true);

    }//GEN-LAST:event_jBike_LMouseClicked

    private void jTruck_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTruck_LMouseClicked
        // TODO add your handling code here:
         new Truck().setVisible(true);
    }//GEN-LAST:event_jTruck_LMouseClicked

    private void jJet_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJet_LMouseClicked
        // TODO add your handling code here:
         new Jet().setVisible(true);
    }//GEN-LAST:event_jJet_LMouseClicked

    private void jAccount_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccount_BTActionPerformed
        // TODO add your handling code here:
        new My_Account().setVisible(true);
        dispose();
}//GEN-LAST:event_jAccount_BTActionPerformed

    private void jCars_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCars_LMouseEntered
        // TODO add your handling code here:
        jCars_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jCars_LMouseEntered

    private void jBike_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBike_LMouseEntered
        // TODO add your handling code here:
      jBike_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBike_LMouseEntered

    private void jTruck_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTruck_LMouseEntered
        // TODO add your handling code here:
        jTruck_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jTruck_LMouseEntered

    private void jJet_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJet_LMouseEntered
        // TODO add your handling code here:
        jJet_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jJet_LMouseEntered

    private void jAbout_us_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbout_us_BTActionPerformed
        // TODO add your handling code here:
        new About_us().setVisible(true);
           dispose();
}//GEN-LAST:event_jAbout_us_BTActionPerformed

    private void jLog_Out_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog_Out_BTActionPerformed
        // TODO add your handling code here:
        new First_Window().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLog_Out_BTActionPerformed

    private void jAccount_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAccount_BTMouseEntered
        // TODO add your handling code here:
        jAccount_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_jAccount_BTMouseEntered

    private void jAbout_us_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAbout_us_BTMouseEntered
        // TODO add your handling code here:
        jAbout_us_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jAbout_us_BTMouseEntered

    private void jLog_Out_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLog_Out_BTMouseEntered
        // TODO add your handling code here:
        jLog_Out_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLog_Out_BTMouseEntered

    private void jWebsite_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jWebsite_LMouseEntered
        // TODO add your handling code here:
        jWebsite_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
}//GEN-LAST:event_jWebsite_LMouseEntered

    private void jWebsite_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jWebsite_LMouseClicked
        // TODO add your handling code here:
         try{
            if(Desktop.isDesktopSupported()){
                Desktop desktop=Desktop.getDesktop();
                if(desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI ("https://www.google.co.in"));
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jWebsite_LMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])  {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAbout_us_BT;
    private javax.swing.JButton jAccount_BT;
    private javax.swing.JLabel jBike_L;
    private javax.swing.JLabel jCars_L;
    private javax.swing.JLabel jJet_L;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLog_Out_BT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jTruck_L;
    private javax.swing.JLabel jWebsite_L;
    // End of variables declaration//GEN-END:variables

}
