/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Your_Orders.java
 *
 * Created on 11 Dec, 2018, 6:35:38 AM
 */

package cars;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DEll
 */
public class Your_Orders extends javax.swing.JFrame {

    /** Creates new form Your_Orders */
    public Your_Orders() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOrders_TB = new javax.swing.JTable();
        jModel_TF = new javax.swing.JTextField();
        jSearch_BT = new javax.swing.JButton();
        jSearch_All_BT = new javax.swing.JButton();
        jBack_L = new javax.swing.JLabel();
        jDelete_BT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("D:\\Apps\\k\\a\\s\\form.jpg").getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Orders", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Nyala", 0, 36), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel1.setOpaque(false);

        jOrders_TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vehicle", "Model_no", "Date", "Quantity", "Price ( Rs )"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jOrders_TB.setToolTipText("");
        jOrders_TB.setGridColor(new java.awt.Color(0, 102, 102));
        jOrders_TB.setRowHeight(20);
        jOrders_TB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jOrders_TBPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jOrders_TB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 70, 663, 250);

        jModel_TF.setFont(new java.awt.Font("Century", 0, 12));
        jModel_TF.setToolTipText("Enter vehicle Model_no");
        getContentPane().add(jModel_TF);
        jModel_TF.setBounds(90, 280, 100, 30);

        jSearch_BT.setFont(new java.awt.Font("Nyala", 0, 18));
        jSearch_BT.setText("Search");
        jSearch_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSearch_BTMouseEntered(evt);
            }
        });
        jSearch_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearch_BTActionPerformed(evt);
            }
        });
        getContentPane().add(jSearch_BT);
        jSearch_BT.setBounds(210, 280, 90, 33);

        jSearch_All_BT.setFont(new java.awt.Font("Nyala", 0, 18));
        jSearch_All_BT.setText("Search All");
        jSearch_All_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearch_All_BTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSearch_All_BTMouseEntered(evt);
            }
        });
        getContentPane().add(jSearch_All_BT);
        jSearch_All_BT.setBounds(480, 280, 120, 33);

        jBack_L.setBackground(new java.awt.Color(255, 255, 255));
        jBack_L.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jBack_L.setForeground(new java.awt.Color(51, 0, 51));
        jBack_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/back.png"))); // NOI18N
        jBack_L.setText("Back");
        jBack_L.setOpaque(true);
        jBack_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack_LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBack_LMouseEntered(evt);
            }
        });
        getContentPane().add(jBack_L);
        jBack_L.setBounds(0, 0, 80, 30);

        jDelete_BT.setFont(new java.awt.Font("Nyala", 0, 18));
        jDelete_BT.setText("Delete");
        jDelete_BT.setPreferredSize(new java.awt.Dimension(75, 29));
        jDelete_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDelete_BTActionPerformed(evt);
            }
        });
        jDelete_BT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDelete_BTPropertyChange(evt);
            }
        });
        getContentPane().add(jDelete_BT);
        jDelete_BT.setBounds(310, 280, 100, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars/123.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-110, -10, 810, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearch_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearch_BTActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel table=(DefaultTableModel)jOrders_TB.getModel();
        int rows=table.getRowCount();
        while(rows>0){
            table.removeRow(0);
            rows--;
        }
        String model_no=jModel_TF.getText();
        try{
             Class.forName("java.sql.Driver");
                Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
                 Statement stmt=con.createStatement();
                 String query="select* from orders where model_no='"+model_no+"';";
                 ResultSet rs=stmt.executeQuery(query);
        while(rs.next()){
            if(model_no.equals(rs.getString("model_No")))
            { jDelete_BT.setVisible(true);
                 String vehicle=rs.getString("vehicle");
                 String modelno=rs.getString("model_no");
                 String date=rs.getString("date");
                 int quantity=rs.getInt("quantity");
                 int price=rs.getInt("price");

                 table.addRow(new Object[]{vehicle,modelno,date,quantity,price});
                
                  }
            else
            { JOptionPane.showMessageDialog(this, "Record not Found");}
        }
                
                 rs.close();
                 stmt.close();
                 con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

}//GEN-LAST:event_jSearch_BTActionPerformed

    private void jBack_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseClicked
        // TODO add your handling code here:
        new My_Account().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBack_LMouseClicked

    private void jBack_LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_LMouseEntered
        // TODO add your handling code here:
        jBack_L.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBack_LMouseEntered

    private void jSearch_All_BTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearch_All_BTMouseClicked
        // TODO add your handling code here:
        DefaultTableModel table=(DefaultTableModel)jOrders_TB.getModel();
        int rows=table.getRowCount();
        while(rows>0){
            table.removeRow(0);
            rows--;
        }

        try{
             Class.forName("java.sql.Driver");
                Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
                 Statement stmt=con.createStatement();
                 String query="select* from orders ;";
                 ResultSet rs=stmt.executeQuery(query);
        while(rs.next()){
                 String vehicle=rs.getString("vehicle");
                 String modelno=rs.getString("model_no");
                 String date=rs.getString("date");
                 int quantity=rs.getInt("quantity");
                 int price=rs.getInt("price");

                 table.addRow(new Object[]{vehicle,modelno,date,quantity,price});
                  }

                 rs.close();
                 stmt.close();
                 con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        
    }//GEN-LAST:event_jSearch_All_BTMouseClicked

    private void jSearch_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearch_BTMouseEntered
        // TODO add your handling code here:
        jSearch_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jSearch_BTMouseEntered

    private void jSearch_All_BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearch_All_BTMouseEntered
        // TODO add your handling code here:
        jSearch_All_BT.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jSearch_All_BTMouseEntered

    private void jDelete_BTPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDelete_BTPropertyChange
        // TODO add your handling code here:
        jDelete_BT.setVisible(false);

    }//GEN-LAST:event_jDelete_BTPropertyChange

    private void jDelete_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDelete_BTActionPerformed
        // TODO add your handling code here:
        String model=jModel_TF.getText();
        try{
             Class.forName("java.sql.Driver");
                Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
                 Statement stmt=con.createStatement();

                 String query="delete from orders where model_No='"+model+"';";
                 int rowseffected=stmt.executeUpdate(query);
                 JOptionPane.showMessageDialog(this, "Records of Vehicle with Model_No "+model+" has been Deleted");
                 con.close();
                 stmt.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


        DefaultTableModel table=(DefaultTableModel)jOrders_TB.getModel();
        int rows=table.getRowCount();
        while(rows>0){
            table.removeRow(0);
            rows--;
        }

        try{
             Class.forName("java.sql.Driver");
                Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
                 Statement stmt=con.createStatement();
                 String query="select* from orders where model_no<>'"+model+"';";
                 ResultSet rs=stmt.executeQuery(query);
        while(rs.next()){
                 String vehicle=rs.getString("vehicle");
                 String modelno=rs.getString("model_no");
                 String date=rs.getString("date");
                 int quantity=rs.getInt("quantity");
                 int price=rs.getInt("price");

                 table.addRow(new Object[]{vehicle,modelno,date,quantity,price});
                  }

                 rs.close();
                 stmt.close();
                 con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jModel_TF.setText("");
    }//GEN-LAST:event_jDelete_BTActionPerformed

    private void jOrders_TBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jOrders_TBPropertyChange
        // TODO add your handling code here:
         DefaultTableCellRenderer stringRenderer = (DefaultTableCellRenderer)
     jOrders_TB.getDefaultRenderer(String.class);
stringRenderer.setHorizontalAlignment(SwingConstants.CENTER);
    }//GEN-LAST:event_jOrders_TBPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel table=(DefaultTableModel)jOrders_TB.getModel();
        int rows=table.getRowCount();
        while(rows>0){
            table.removeRow(0);
            rows--;
        }

        try{
             Class.forName("java.sql.Driver");
                Connection con=(Connection)DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/cars","root","");
                 Statement stmt=con.createStatement();

                 String query="select* from orders ;";
                 ResultSet rs=stmt.executeQuery(query);
                 rs.last();

        
                 String vehicle=rs.getString("vehicle");
                 String modelno=rs.getString("model_no");
                 String date=rs.getString("date");
                 int quantity=rs.getInt("quantity");
                 int price=rs.getInt("price");

                 table.addRow(new Object[]{vehicle,modelno,date,quantity,price});
                  

                 rs.close();
                 stmt.close();
                 con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Your_Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBack_L;
    private javax.swing.JButton jDelete_BT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jModel_TF;
    private javax.swing.JTable jOrders_TB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearch_All_BT;
    private javax.swing.JButton jSearch_BT;
    // End of variables declaration//GEN-END:variables

}
